"""Stack Machine Target Code Generator for GenZ/Brainrot language.

Phase 6 (Target Code) — Generates low-level Stack Machine instructions
from the GenZ AST. This is the final compilation target — a virtual
machine with a stack-based instruction set.

Instruction Set:
    PUSH <val>          Push a constant onto the stack
    LOAD <var>          Load a variable's value onto the stack
    STORE <var>         Pop top of stack and store in variable
    LOAD_IDX            Pop index then array; push array[index]
    STORE_IDX <var>     Pop value then index; store in array[index]
    MAKE_ARRAY <n>      Pop n values and create an array
    ADD                 Pop two values, push their sum
    SUB                 Pop two values, push left - right
    MUL                 Pop two values, push their product
    DIV                 Pop two values, push left / right
    MOD                 Pop two values, push left % right
    NEG                 Pop one value, push its negation
    NOT                 Pop one value, push logical NOT
    CMP_EQ              Pop two, push 1 if equal else 0
    CMP_NEQ             Pop two, push 1 if not equal else 0
    CMP_LT              Pop two, push 1 if left < right else 0
    CMP_GT              Pop two, push 1 if left > right else 0
    CMP_LTE             Pop two, push 1 if left <= right else 0
    CMP_GTE             Pop two, push 1 if left >= right else 0
    AND                 Pop two, push logical AND
    OR                  Pop two, push logical OR
    JMP <label>         Unconditional jump to label
    JMP_FALSE <label>   Pop top; jump to label if it is 0/false
    CALL <name> <nargs> Call function with nargs args from stack
    RETURN              Return top of stack from current function
    RETURN_VOID         Return from function with no value
    PRINT               Pop top of stack and print it
    LABEL <name>        Define a jump target label
    FUNC_START <name>   Mark the start of a function body
    FUNC_END <name>     Mark the end of a function body
    HALT                Stop execution
"""

from src.parser.ast import (
    Program, VarDecl, FuncDecl, Assignment, PrintStmt,
    IfStmt, SwitchStmt, WhileStmt, ForStmt, ReturnStmt,
    BreakStmt, ContinueStmt, ExprStmt, Block,
    Binary, Unary, Literal, Variable, ArrayAccess, ArrayLiteral, FuncCall
)


class StackMachineGenerator:
    """Translates a GenZ AST to Stack Machine instructions.

    The generated code targets a simple stack-based virtual machine
    where all operands are passed via a runtime stack.
    """

    # Map GenZ binary operators to stack machine instructions
    _OP_MAP = {
        "+":  "ADD",
        "-":  "SUB",
        "*":  "MUL",
        "/":  "DIV",
        "%":  "MOD",
        "==": "CMP_EQ",
        "!=": "CMP_NEQ",
        "<":  "CMP_LT",
        ">":  "CMP_GT",
        "<=": "CMP_LTE",
        ">=": "CMP_GTE",
        "&&": "AND",
        "||": "OR",
    }

    def __init__(self):
        self._instructions: list[str] = []
        self._label_count: int = 0
        # Stack of (continue_label, break_label) per loop
        self._loop_stack: list[tuple[str, str]] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, ast: Program) -> str:
        """Generate stack machine code from the AST."""
        self._instructions = []
        self._label_count = 0
        self._loop_stack = []

        self._emit("; =============================================")
        self._emit("; Stack Machine Target Code")
        self._emit("; Generated by GenZCode Stack Machine Generator")
        self._emit("; =============================================")
        self._emit("")
        self._visit_program(ast)
        self._emit("HALT")
        return "\n".join(self._instructions)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _new_label(self, prefix: str = "L") -> str:
        label = f"{prefix}{self._label_count}"
        self._label_count += 1
        return label

    def _emit(self, instruction: str) -> None:
        self._instructions.append(instruction)

    def _emit_label(self, label: str) -> None:
        self._instructions.append(f"{label}:")

    def _emit_comment(self, comment: str) -> None:
        self._instructions.append(f"; {comment}")

    # ------------------------------------------------------------------
    # Statement visitors
    # ------------------------------------------------------------------

    def _visit_program(self, node: Program) -> None:
        # Emit global statements first (non-functions)
        for stmt in node.statements:
            if not isinstance(stmt, FuncDecl):
                self._visit(stmt)
        # Emit function definitions at the end
        for stmt in node.statements:
            if isinstance(stmt, FuncDecl):
                self._visit(stmt)

    def _visit(self, node) -> None:
        method = f"_visit_{type(node).__name__}"
        if hasattr(self, method):
            getattr(self, method)(node)

    def _visit_VarDecl(self, node: VarDecl) -> None:
        self._emit_comment(f"declare {node.name}: {node.type_name}")
        if node.initializer:
            self._visit_expr(node.initializer)  # value → stack
        else:
            # Push default value
            if node.type_name == "txt":
                self._emit('PUSH ""')
            elif node.type_name.endswith("[]"):
                self._emit("MAKE_ARRAY 0")
            else:
                self._emit("PUSH 0")
        self._emit(f"STORE {node.name}")

    def _visit_Assignment(self, node: Assignment) -> None:
        self._visit_expr(node.value)   # value → stack
        if isinstance(node.target, ArrayAccess):
            self._visit_expr(node.target.index)   # index → stack
            self._emit(f"STORE_IDX {node.target.array.name}")
        else:
            self._emit(f"STORE {node.target.name}")

    def _visit_PrintStmt(self, node: PrintStmt) -> None:
        for arg in node.arguments:
            self._visit_expr(arg)   # value → stack
            self._emit("PRINT")

    def _visit_IfStmt(self, node: IfStmt) -> None:
        label_else = self._new_label("ELSE_")
        label_end  = self._new_label("ENDIF_")
        self._emit_comment("--- if ---")
        self._visit_expr(node.condition)   # condition → stack
        self._emit(f"JMP_FALSE {label_else}")
        if node.then_branch:
            self._visit(node.then_branch)
        self._emit(f"JMP {label_end}")
        self._emit_label(label_else)
        if node.else_branch:
            self._visit(node.else_branch)
        self._emit_label(label_end)
        self._emit_comment("--- end if ---")

    def _visit_WhileStmt(self, node: WhileStmt) -> None:
        label_start = self._new_label("WHILE_")
        label_end   = self._new_label("ENDWHILE_")
        self._loop_stack.append((label_start, label_end))
        self._emit_comment("--- while ---")
        self._emit_label(label_start)
        self._visit_expr(node.condition)   # condition → stack
        self._emit(f"JMP_FALSE {label_end}")
        if node.body:
            self._visit(node.body)
        self._emit(f"JMP {label_start}")
        self._emit_label(label_end)
        self._emit_comment("--- end while ---")
        self._loop_stack.pop()

    def _visit_ForStmt(self, node: ForStmt) -> None:
        label_start  = self._new_label("FOR_")
        label_end    = self._new_label("ENDFOR_")
        label_update = self._new_label("FORUPD_")
        self._loop_stack.append((label_update, label_end))
        self._emit_comment("--- for ---")
        if node.init:
            self._visit(node.init)
        self._emit_label(label_start)
        if node.condition:
            self._visit_expr(node.condition)
            self._emit(f"JMP_FALSE {label_end}")
        if node.body:
            self._visit(node.body)
        self._emit_label(label_update)
        if node.update:
            self._visit_expr(node.update)
            # Discard the value left on the stack by the update expression
            self._emit("; discard update expression result")
        self._emit(f"JMP {label_start}")
        self._emit_label(label_end)
        self._emit_comment("--- end for ---")
        self._loop_stack.pop()

    def _visit_ReturnStmt(self, node: ReturnStmt) -> None:
        if node.value:
            self._visit_expr(node.value)
            self._emit("RETURN")
        else:
            self._emit("RETURN_VOID")

    def _visit_BreakStmt(self, node: BreakStmt) -> None:
        if self._loop_stack:
            _, end_label = self._loop_stack[-1]
            self._emit(f"JMP {end_label}  ; break")

    def _visit_ContinueStmt(self, node: ContinueStmt) -> None:
        if self._loop_stack:
            continue_label, _ = self._loop_stack[-1]
            self._emit(f"JMP {continue_label}  ; continue")

    def _visit_FuncDecl(self, node: FuncDecl) -> None:
        self._emit("")
        self._emit_comment(f"--- function {node.name} ---")
        self._emit(f"FUNC_START {node.name}")
        # Parameters: at call time they are pushed left-to-right, so the
        # function body STOREs them from the top of the stack in reverse.
        for param in reversed(node.params):
            self._emit(f"STORE {param.name}  ; param")
        if node.body:
            self._visit(node.body)
        self._emit(f"FUNC_END {node.name}")
        self._emit_comment(f"--- end function {node.name} ---")
        self._emit("")

    def _visit_ExprStmt(self, node: ExprStmt) -> None:
        self._visit_expr(node.expression)

    def _visit_Block(self, node: Block) -> None:
        for stmt in node.statements:
            self._visit(stmt)

    def _visit_SwitchStmt(self, node: SwitchStmt) -> None:
        label_end = self._new_label("ENDSWITCH_")
        self._emit_comment("--- switch ---")
        # Generate variable to hold the switch expression once
        switch_var = f"__sw{self._label_count}"
        self._visit_expr(node.expression)
        self._emit(f"STORE {switch_var}")
        for case_val, case_stmts in node.cases:
            label_next = self._new_label("CASE_SKIP_")
            self._emit(f"LOAD {switch_var}")
            self._visit_expr(case_val)
            self._emit("CMP_EQ")
            self._emit(f"JMP_FALSE {label_next}")
            for stmt in case_stmts:
                self._visit(stmt)
            self._emit(f"JMP {label_end}")
            self._emit_label(label_next)
        if node.default:
            self._emit_comment("default:")
            for stmt in node.default:
                self._visit(stmt)
        self._emit_label(label_end)
        self._emit_comment("--- end switch ---")

    # ------------------------------------------------------------------
    # Expression code gen (each leaves exactly one value on the stack)
    # ------------------------------------------------------------------

    def _visit_expr(self, expr) -> None:
        method = f"_expr_{type(expr).__name__}"
        if hasattr(self, method):
            getattr(self, method)(expr)
        else:
            self._emit(f"; unknown expr {type(expr).__name__}")

    def _expr_Literal(self, expr: Literal) -> None:
        if isinstance(expr.value, bool):
            self._emit(f"PUSH {1 if expr.value else 0}")
        elif isinstance(expr.value, str):
            self._emit(f'PUSH "{expr.value}"')
        else:
            self._emit(f"PUSH {expr.value}")

    def _expr_Variable(self, expr: Variable) -> None:
        self._emit(f"LOAD {expr.name}")

    def _expr_ArrayAccess(self, expr: ArrayAccess) -> None:
        self._visit_expr(expr.array)   # array ref → stack
        self._visit_expr(expr.index)   # index → stack
        self._emit("LOAD_IDX")

    def _expr_ArrayLiteral(self, expr: ArrayLiteral) -> None:
        for element in expr.elements:
            self._visit_expr(element)
        self._emit(f"MAKE_ARRAY {len(expr.elements)}")

    def _expr_Binary(self, expr: Binary) -> None:
        self._visit_expr(expr.left)    # left → stack
        self._visit_expr(expr.right)   # right → stack
        instruction = self._OP_MAP.get(expr.operator, f"; unknown op {expr.operator}")
        self._emit(instruction)

    def _expr_Unary(self, expr: Unary) -> None:
        self._visit_expr(expr.operand)
        if expr.operator == "-":
            self._emit("NEG")
        elif expr.operator == "!":
            self._emit("NOT")

    def _expr_FuncCall(self, expr: FuncCall) -> None:
        # Push arguments left-to-right
        for arg in expr.arguments:
            self._visit_expr(arg)
        self._emit(f"CALL {expr.name} {len(expr.arguments)}")

    def _expr_Assignment(self, expr: Assignment) -> None:
        self._visit_expr(expr.value)
        self._emit(f"STORE {expr.target.name}")
        # Leave the value on the stack (assignment is also an expression)
        self._emit(f"LOAD {expr.target.name}")


def generate_stack_code(ast: Program) -> str:
    """Convenience function: generate stack machine code from AST."""
    return StackMachineGenerator().generate(ast)


# =============================================================================
# Standalone entry point: python src/codegen/stack_machine.py input.genz
# =============================================================================

if __name__ == "__main__":
    import sys
    from src.lexer import tokenize
    from src.parser.parser import Parser
    from src.semantic.analyzer import SemanticAnalyzer

    if len(sys.argv) < 2:
        print("Usage: python src/codegen/stack_machine.py <input.genz>")
        print("       python -m src.codegen.stack_machine <input.genz>")
        sys.exit(1)

    input_file = sys.argv[1]
    try:
        with open(input_file, "r", encoding="utf-8") as f:
            source = f.read()
    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found.", file=sys.stderr)
        sys.exit(1)

    try:
        tokens = tokenize(source)
        ast = Parser(tokens).parse()
        SemanticAnalyzer().analyze(ast)
        code = generate_stack_code(ast)
        print("=== Stack Machine Target Code ===")
        print(code)
        print("=== End of Target Code ===")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
