"""Intermediate Code Generator for GenZ/Brainrot language.

Phase 4 — Generates Three-Address Code (TAC) from the AST.

Three-Address Code format:
    t0 = a + b          (binary expression)
    t1 = -x             (unary expression)
    x = t0              (assignment)
    print t0            (print statement)
    ifnot t1 goto L0    (conditional jump)
    goto L1             (unconditional jump)
    L0:                 (label)
    func foo            (function start)
    endfunc foo         (function end)
    t2 = call foo(a, b) (function call)
    return t2           (return statement)

Standalone usage:
    python -m src.ir.ir_generator input.genz
    python src/ir/ir_generator.py input.genz
"""

import sys
import os
from pathlib import Path

# Allow running as a standalone script
if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from Phase2_Syntax.genz_ast import (
    Program, VarDecl, FuncDecl, Assignment, PrintStmt,
    IfStmt, SwitchStmt, WhileStmt, ForStmt, ReturnStmt,
    BreakStmt, ContinueStmt, ExprStmt, Block,
    Binary, Unary, Literal, Variable, ArrayAccess, ArrayLiteral, FuncCall
)


class IRGenerator:
    """Generates Three-Address Code (TAC) from a GenZ AST.

    Each instruction has at most one operator, making the code
    suitable for optimization and further translation.
    """

    def __init__(self):
        self.instructions: list[str] = []
        self.temp_count: int = 0
        self.label_count: int = 0
        # Stack of (start_label, end_label) for break/continue
        self._loop_stack: list[tuple[str, str]] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, ast: Program) -> str:
        """Generate TAC from the AST and return as a string."""
        self.instructions = []
        self.temp_count = 0
        self.label_count = 0
        self._loop_stack = []

        self.instructions.append("; === Three-Address Code (TAC) ===")
        self.instructions.append("; Generated by GenZCode IR Generator")
        self.instructions.append("")
        self._visit_program(ast)
        return "\n".join(self.instructions)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _new_temp(self) -> str:
        t = f"t{self.temp_count}"
        self.temp_count += 1
        return t

    def _new_label(self) -> str:
        label = f"L{self.label_count}"
        self.label_count += 1
        return label

    def _emit(self, code: str) -> None:
        self.instructions.append(code)

    def _emit_comment(self, comment: str) -> None:
        self.instructions.append(f"; {comment}")

    # ------------------------------------------------------------------
    # Statement visitors
    # ------------------------------------------------------------------

    def _visit_program(self, node: Program) -> None:
        for stmt in node.statements:
            self._visit(stmt)

    def _visit(self, node) -> None:
        method = f"_visit_{type(node).__name__}"
        if hasattr(self, method):
            getattr(self, method)(node)

    def _visit_VarDecl(self, node: VarDecl) -> None:
        self._emit_comment(f"var {node.name}: {node.type_name}")
        if node.initializer:
            result = self._visit_expr(node.initializer)
            self._emit(f"{node.name} = {result}")
        else:
            default = '""' if node.type_name == "txt" else ("[]" if node.type_name.endswith("[]") else "0")
            self._emit(f"{node.name} = {default}")

    def _visit_FuncDecl(self, node: FuncDecl) -> None:
        self._emit("")
        params = ", ".join(p.name for p in node.params)
        self._emit(f"func {node.name}({params})")
        if node.body:
            for stmt in node.body.statements:
                self._visit(stmt)
        self._emit(f"endfunc {node.name}")
        self._emit("")

    def _visit_PrintStmt(self, node: PrintStmt) -> None:
        for arg in node.arguments:
            result = self._visit_expr(arg)
            self._emit(f"print {result}")

    def _visit_IfStmt(self, node: IfStmt) -> None:
        self._emit_comment("if statement")
        cond = self._visit_expr(node.condition)
        label_else = self._new_label()
        label_end = self._new_label()
        self._emit(f"ifnot {cond} goto {label_else}")
        if node.then_branch:
            self._visit(node.then_branch)
        self._emit(f"goto {label_end}")
        self._emit(f"{label_else}:")
        if node.else_branch:
            self._visit(node.else_branch)
        self._emit(f"{label_end}:")

    def _visit_WhileStmt(self, node: WhileStmt) -> None:
        label_start = self._new_label()
        label_end = self._new_label()
        self._loop_stack.append((label_start, label_end))
        self._emit_comment("while loop")
        self._emit(f"{label_start}:")
        cond = self._visit_expr(node.condition)
        self._emit(f"ifnot {cond} goto {label_end}")
        if node.body:
            self._visit(node.body)
        self._emit(f"goto {label_start}")
        self._emit(f"{label_end}:")
        self._loop_stack.pop()

    def _visit_ForStmt(self, node: ForStmt) -> None:
        label_start = self._new_label()
        label_end = self._new_label()
        self._loop_stack.append((label_start, label_end))
        self._emit_comment("for loop")
        if node.init:
            self._visit(node.init)
        self._emit(f"{label_start}:")
        if node.condition:
            cond = self._visit_expr(node.condition)
            self._emit(f"ifnot {cond} goto {label_end}")
        if node.body:
            self._visit(node.body)
        if node.update:
            result = self._visit_expr(node.update)
            if "=" not in result:
                self._emit(result)
        self._emit(f"goto {label_start}")
        self._emit(f"{label_end}:")
        self._loop_stack.pop()

    def _visit_ReturnStmt(self, node: ReturnStmt) -> None:
        if node.value:
            result = self._visit_expr(node.value)
            self._emit(f"return {result}")
        else:
            self._emit("return")

    def _visit_BreakStmt(self, node: BreakStmt) -> None:
        if self._loop_stack:
            _, end_label = self._loop_stack[-1]
            self._emit(f"goto {end_label}  ; break")
        else:
            self._emit("goto endloop  ; break")

    def _visit_ContinueStmt(self, node: ContinueStmt) -> None:
        if self._loop_stack:
            start_label, _ = self._loop_stack[-1]
            self._emit(f"goto {start_label}  ; continue")
        else:
            self._emit("goto loopstart  ; continue")

    def _visit_ExprStmt(self, node: ExprStmt) -> None:
        self._visit_expr(node.expression)

    def _visit_Block(self, node: Block) -> None:
        for stmt in node.statements:
            self._visit(stmt)

    def _visit_SwitchStmt(self, node: SwitchStmt) -> None:
        self._emit_comment("switch statement")
        expr = self._visit_expr(node.expression)
        end_label = self._new_label()
        for case_val, case_stmts in node.cases:
            cv = self._visit_expr(case_val)
            label_case = self._new_label()
            label_skip = self._new_label()
            t = self._new_temp()
            self._emit(f"{t} = {expr} == {cv}")
            self._emit(f"ifnot {t} goto {label_skip}")
            self._emit(f"{label_case}:")
            for stmt in case_stmts:
                self._visit(stmt)
            self._emit(f"goto {end_label}")
            self._emit(f"{label_skip}:")
        if node.default:
            self._emit_comment("default case")
            for stmt in node.default:
                self._visit(stmt)
        self._emit(f"{end_label}:")

    def _visit_Assignment(self, node: Assignment) -> None:
        result = self._visit_expr(node.value)
        target = self._visit_expr(node.target)
        self._emit(f"{target} = {result}")

    # ------------------------------------------------------------------
    # Expression visitors (return the temp/name holding the value)
    # ------------------------------------------------------------------

    def _visit_expr(self, expr) -> str:
        method = f"_expr_{type(expr).__name__}"
        if hasattr(self, method):
            return getattr(self, method)(expr)
        return str(getattr(expr, "value", expr))

    def _expr_Literal(self, expr: Literal) -> str:
        if isinstance(expr.value, str):
            return f'"{expr.value}"'
        if isinstance(expr.value, bool):
            return "1" if expr.value else "0"
        return str(expr.value)

    def _expr_Variable(self, expr: Variable) -> str:
        return expr.name

    def _expr_ArrayAccess(self, expr: ArrayAccess) -> str:
        arr = self._visit_expr(expr.array)
        idx = self._visit_expr(expr.index)
        t = self._new_temp()
        self._emit(f"{t} = {arr}[{idx}]")
        return t

    def _expr_ArrayLiteral(self, expr: ArrayLiteral) -> str:
        elements = [self._visit_expr(e) for e in expr.elements]
        t = self._new_temp()
        self._emit(f"{t} = [{', '.join(elements)}]")
        return t

    def _expr_Binary(self, expr: Binary) -> str:
        left = self._visit_expr(expr.left)
        right = self._visit_expr(expr.right)
        op = expr.operator
        # Convert GenZ ops to readable TAC ops
        if op == "&&":
            op = "AND"
        elif op == "||":
            op = "OR"
        t = self._new_temp()
        self._emit(f"{t} = {left} {op} {right}")
        return t

    def _expr_Unary(self, expr: Unary) -> str:
        operand = self._visit_expr(expr.operand)
        op = "NOT" if expr.operator == "!" else expr.operator
        t = self._new_temp()
        self._emit(f"{t} = {op} {operand}")
        return t

    def _expr_FuncCall(self, expr: FuncCall) -> str:
        args = [self._visit_expr(a) for a in expr.arguments]
        t = self._new_temp()
        self._emit(f"{t} = call {expr.name}({', '.join(args)})")
        return t

    def _expr_Assignment(self, expr: Assignment) -> str:
        result = self._visit_expr(expr.value)
        target = self._visit_expr(expr.target)
        self._emit(f"{target} = {result}")
        return target


def generate_ir(ast: Program) -> str:
    """Convenience function: generate TAC from AST."""
    return IRGenerator().generate(ast)


# =============================================================================
# Standalone entry point: python src/ir/ir_generator.py input.genz
# =============================================================================

if __name__ == "__main__":
    from Phase1_Lexical.lexer import tokenize
    from Phase2_Syntax.parser import Parser

    if len(sys.argv) < 2:
        print("Usage: python src/ir/ir_generator.py <input.genz>")
        print("       python -m src.ir.ir_generator <input.genz>")
        sys.exit(1)

    input_file = sys.argv[1]
    try:
        with open(input_file, "r", encoding="utf-8") as f:
            source = f.read()
    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found.", file=sys.stderr)
        sys.exit(1)

    try:
        tokens = tokenize(source)
        ast = Parser(tokens).parse()
        ir_code = generate_ir(ast)
        print("=== Three-Address Code (TAC) ===")
        print(ir_code)
        print("=== End of IR ===")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
